### ISSUE TITLE
AttributeError: 'LanguageField' object has no attribute 'db_collation'

### ISSUE THREAD

**Issue by lorenzo-dallamuta** [audiolion/django-language-field#5]
Getting this on version 0.0.3 with Django 3.2 using the default SQLite back-end.

**Comment by dellsystem** [comment]
I also got this error and was able to work around it by adding self.db_collation = False to languages/fields.py in [my fork](https://github.com/dellsystem/django-language-field/commit/64eb0e21b6857f62206255ba0e23e96b47828e97), and using my fork as the source for this package rather than pypi

**Comment by audiolion** [comment]
Fixed in #8
